apiVersion: v1
kind: Service
metadata:
  name: courses-api
  namespace: courses-system

spec:
  selector:
    app: courses

  type: ClusterIP

  ports:
  - name: courses-api
    port: 3000
    targetPort: courses-api
  - name: courses-api-debug
    port: 4000
    targetPort: courses-api-debug