apiVersion: v1
kind: Namespace
metadata:
  name: courses-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses
  namespace: courses-system

spec:
  selector:
    matchLabels:
      app: courses

  template:
    metadata:
      labels:
        app: courses
    
    spec:
      terminationGracePeriodSeconds: 60

      containers:
      - name: courses-api
        image: courses-service-image

        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu